import streamlit as st
import pandas as pd
import json
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="AI Evaluator Bias Explorer", layout="wide")

st.title("Do AI judges play favorites?")
st.subheader("Interactive Explorer for the Self-Preference & Self-Recognition Dataset")

st.markdown('''
This dashboard allows you to interactively explore the dataset generated by four frontier AI models 
(Claude Opus 4.7, Gemini 3.1 Pro, GPT-5.5, and Kimi K2.6) judging each other's outputs.

The primary finding of our research is that **perceived authorship drives self-preference**, but judges exhibit 
**extreme heterogeneity** in how they perceive and reward it.
''')

@st.cache_data
def load_data():
    wide_df = pd.read_csv("data/unified/unified_wide.csv")
    long_df = pd.read_csv("data/unified/unified_long.csv")
    return wide_df, long_df

try:
    wide_df, long_df = load_data()
    
    st.sidebar.header("Filters")
    selected_judge = st.sidebar.selectbox("Select Judge Model", ["All"] + list(wide_df["judge"].unique()))
    selected_author = st.sidebar.selectbox("Select Author Model", ["All"] + list(wide_df["author"].unique()))
    selected_condition = st.sidebar.selectbox("Select Condition", ["All"] + list(wide_df["condition"].unique()))
    
    filtered_wide = wide_df.copy()
    filtered_long = long_df.copy()
    
    if selected_judge != "All":
        filtered_wide = filtered_wide[filtered_wide["judge"] == selected_judge]
        filtered_long = filtered_long[filtered_long["judge"] == selected_judge]
    if selected_author != "All":
        filtered_wide = filtered_wide[filtered_wide["author"] == selected_author]
        filtered_long = filtered_long[filtered_long["author"] == selected_author]
    if selected_condition != "All":
        filtered_wide = filtered_wide[filtered_wide["condition"] == selected_condition]
        filtered_long = filtered_long[filtered_long["condition"] == selected_condition]
        
    st.header("Score Distribution Explorer")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("Score Distribution by Judge")
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.violinplot(data=filtered_wide, x="judge", y="composite", ax=ax)
        plt.xticks(rotation=45)
        st.pyplot(fig)
        
    with col2:
        st.subheader("Score Distribution by Original Author")
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.violinplot(data=filtered_wide, x="author", y="composite", ax=ax)
        plt.xticks(rotation=45)
        st.pyplot(fig)
        
    st.header("Subscale Dissociation")
    st.markdown('''
    We found a profound dissociation between **Form** (clarity, creativity) and **Content** (correctness, completeness).
    ''')
    
    fig2, ax2 = plt.subplots(figsize=(12, 6))
    sns.barplot(data=filtered_long, x="dimension", y="score", hue="judge", ax=ax2)
    plt.xticks(rotation=45)
    st.pyplot(fig2)

    st.header("Belief vs Reality: The Self-Preference Mechanism")

    fig3, ax3 = plt.subplots(figsize=(12, 6))
    sns.barplot(data=filtered_wide, x="judge", y="composite", hue="predicted_self", ax=ax3)
    ax3.set_title("Composite Score by Perceived Authorship")
    ax3.set_ylim(0, 11)
    ax3.tick_params(axis="x", rotation=45)
    fig3.tight_layout()
    st.pyplot(fig3)

    fig4, ax4 = plt.subplots(figsize=(12, 6))
    sns.barplot(data=filtered_wide, x="judge", y="composite", hue="author_is_self", ax=ax4)
    ax4.set_title("Composite Score by Actual Authorship")
    ax4.set_ylim(0, 11)
    ax4.tick_params(axis="x", rotation=45)
    st.pyplot(fig4)

    st.header("Confidence Stratification")

    fig5, ax5 = plt.subplots(figsize=(12, 6))
    sns.barplot(data=filtered_wide, x="judge", y="composite", hue="confidence", ax=ax5)
    ax5.set_title("Composite Score by Judge Confidence")
    ax5.set_ylim(0, 11)
    ax5.tick_params(axis="x", rotation=45)
    fig5.tight_layout()
    st.pyplot(fig5)
    
    st.header("Raw Data Table (Wide Format)")
    st.dataframe(filtered_wide)
    
except Exception as e:
    st.error(f"Error loading data: {e}")
