#!/usr/bin/env python3
"""Off-topic sensitivity pass for the subscale × condition belief-vs-style horse-race.

Reruns analysis/subscale_horse_race.py on the same 4-judge × 4-author dataset after
dropping the 11 prompts where Kimi K2.6's original response was off-topic. These 11
prompts create high-leverage low-score rows that can shift b1 (the M->Y coefficient
for verbalised authorship). The "drop-11" pass uses the remaining 19 prompts
(4 authors x 4 judges x 19 prompts = 304 rows per dimension-condition cell). The
style channel (a2·b2 via the 11-feature stylometric LR posterior) is less sensitive
in this descriptive check.

Deterministic: seed=20260512, B=2000 cluster bootstrap on prompt_id. Bootstrap
intervals are descriptive uncertainty summaries, not causal identification.
"""
import os
import sys
import numpy as np
import pandas as pd

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, THIS_DIR)

from subscale_horse_race import (  # noqa: E402
    fit_cell, cluster_bootstrap, ci, fmt_ci,
    REPO, DIMS, CONDS, OFF_TOPIC,
)


def run_pass(df: pd.DataFrame, label: str) -> pd.DataFrame:
    rows = []
    for dim in DIMS:
        for cond in CONDS:
            sub = df[(df["dimension"] == dim) & (df["condition"] == cond)].copy()
            est = fit_cell(sub)
            boot = cluster_bootstrap(sub)
            ip_lo, ip_hi = ci(boot["indirect_pred"])
            is_lo, is_hi = ci(boot["indirect_style"])
            b1_lo, b1_hi = ci(boot["b1"])
            b2_lo, b2_hi = ci(boot["b2"])
            rows.append({
                "label": label, "dimension": dim, "condition": cond, "N": len(sub),
                "indirect_pred": est["indirect_pred"],
                "indirect_pred_lo": ip_lo, "indirect_pred_hi": ip_hi,
                "indirect_style": est["indirect_style"],
                "indirect_style_lo": is_lo, "indirect_style_hi": is_hi,
                "b1": est["b1"], "b1_lo": b1_lo, "b1_hi": b1_hi,
                "b2": est["b2"], "b2_lo": b2_lo, "b2_hi": b2_hi,
                "c": est["c"], "c_prime": est["c_prime"],
            })
    return pd.DataFrame(rows)


def sig(lo: float, hi: float) -> bool:
    return (lo > 0.0) or (hi < 0.0)


def write_report(out: pd.DataFrame, path: str) -> None:
    full = out[out["label"] == "full"].set_index(["dimension", "condition"])
    drop = out[out["label"] == "drop11"].set_index(["dimension", "condition"])
    lines = []
    lines.append("# Off-topic sensitivity: subscale × condition belief-vs-style horse-race\n")
    lines.append("**Generated by** `analysis/subscale_horse_race_off_topic.py`. "
                 "Seed `20260512`, B=2000 cluster bootstrap on `prompt_id`.\n")
    lines.append("**Rationale.** PR #65's pooled belief channel (a1·b1 via `predicted_self`) "
                 "is positive in most rubric-dimension × condition cells, especially completeness, "
                 "creativity, and constraint adherence, while the measured-style channel (a2·b2 via `style_prob_self`) is mostly negative. We "
                 "test how much of the pooled belief signal is driven by 11 prompts on which "
                 "Kimi K2.6's original C1 response was off-topic. Those prompts create "
                 "high-leverage low-score rows whose authorship/recognition pattern can shift "
                 "`b1`. We drop those prompts for **all four authors** (not just Kimi) and "
                 "re-fit. The remaining 19 prompts give N=304 per (dim, cond) cell.\n")
    lines.append("**Drop list (11 prompts where Kimi went off-topic):** "
                 + ", ".join(f"`{p}`" for p in OFF_TOPIC) + "\n")
    lines.append("## Scope caveat\n")
    lines.append("This is an exploratory observed-variable robustness analysis. It reuses `predicted_self` "
                 "from later C4 rather than a manipulated belief variable, and `style_prob_self` is only "
                 "an 11-feature stylometric proxy. Bootstrap intervals below summarize prompt-cluster "
                 "resampling uncertainty; they should not be read as causal mediation estimates or proof "
                 "of a transportable mechanism.\n")
    lines.append("## Headline\n")
    lines.append("- The pooled belief channel **collapses** under drop-11: 7/8 originally-significant "
                 "positive belief cells lose interval support; 4 cells (`correctness×C1/C2/C3`, "
                 "`clarity×C3`) flip sign and have intervals below zero.\n")
    lines.append("- The style channel is **robust**: 14/15 cells preserve sign; 2 cells gain "
                 "descriptive support on the negative side (`correctness×C1`, `clarity×C1`); 1 loses "
                 "such support (`constraint_adherence×C2`).\n")
    lines.append("- Methodological caveat for #65 and #60: the pooled +0.17 belief indirect in "
                 "C1 should not be read as a stable, dataset-general result. Per-judge horse-race "
                 "(Claude +0.10, GPT-5.5 +0.33 in C1) is a more reliable summary.\n")

    lines.append("## Side-by-side table (point [95% CI])\n")
    lines.append("| Dim | Cond | N (full→drop) | Belief full | Belief drop-11 | Style full | Style drop-11 |")
    lines.append("|:---|:---:|:---:|:---|:---|:---|:---|")
    for dim in DIMS:
        for cond in CONDS:
            f = full.loc[(dim, cond)]
            d = drop.loc[(dim, cond)]
            f_belief = fmt_ci(f["indirect_pred"], f["indirect_pred_lo"], f["indirect_pred_hi"])
            d_belief = fmt_ci(d["indirect_pred"], d["indirect_pred_lo"], d["indirect_pred_hi"])
            f_style = fmt_ci(f["indirect_style"], f["indirect_style_lo"], f["indirect_style_hi"])
            d_style = fmt_ci(d["indirect_style"], d["indirect_style_lo"], d["indirect_style_hi"])
            # bold the cells whose CIs exclude 0 after drop
            if sig(d["indirect_pred_lo"], d["indirect_pred_hi"]):
                d_belief = f"**{d_belief}**"
            if sig(d["indirect_style_lo"], d["indirect_style_hi"]):
                d_style = f"**{d_style}**"
            if sig(f["indirect_pred_lo"], f["indirect_pred_hi"]):
                f_belief = f"**{f_belief}**"
            if sig(f["indirect_style_lo"], f["indirect_style_hi"]):
                f_style = f"**{f_style}**"
            lines.append(f"| {dim} | {cond.upper()} | {int(f['N'])}→{int(d['N'])} | "
                         f"{f_belief} | {d_belief} | {f_style} | {d_style} |")
    lines.append("")

    lines.append("## Sign-flip and interval-support summary\n")
    flips_pos_neg = []
    lost_sig = []
    gained_sig_neg = []
    style_changes = []
    for dim in DIMS:
        for cond in CONDS:
            f = full.loc[(dim, cond)]
            d = drop.loc[(dim, cond)]
            f_sig = sig(f["indirect_pred_lo"], f["indirect_pred_hi"])
            d_sig = sig(d["indirect_pred_lo"], d["indirect_pred_hi"])
            if f["indirect_pred"] > 0 and d["indirect_pred"] < 0:
                flips_pos_neg.append(f"{dim}×{cond.upper()}")
            if f_sig and not d_sig:
                lost_sig.append(f"{dim}×{cond.upper()}")
            if d_sig and not f_sig and d["indirect_pred"] < 0:
                gained_sig_neg.append(f"{dim}×{cond.upper()}")
            f_ss = sig(f["indirect_style_lo"], f["indirect_style_hi"])
            d_ss = sig(d["indirect_style_lo"], d["indirect_style_hi"])
            if f_ss != d_ss:
                tag = "GAINED" if d_ss and not f_ss else "LOST"
                style_changes.append(f"{dim}×{cond.upper()} ({tag})")
    lines.append(f"- **Belief: sign flips positive → negative ({len(flips_pos_neg)} cells):** "
                 + (", ".join(flips_pos_neg) if flips_pos_neg else "—") + "\n")
    lines.append(f"- **Belief: lost interval support ({len(lost_sig)} cells):** "
                 + (", ".join(lost_sig) if lost_sig else "—") + "\n")
    lines.append(f"- **Belief: gained interval support on negative side ({len(gained_sig_neg)} cells):** "
                 + (", ".join(gained_sig_neg) if gained_sig_neg else "—") + "\n")
    lines.append(f"- **Style: interval-support changes ({len(style_changes)} cells):** "
                 + (", ".join(style_changes) if style_changes else "—") + "\n")
    lines.append("## Interpretation\n")
    lines.append("The pooled belief channel in PR #65/#60 is substantially driven by Kimi's 11 "
                 "off-topic prompts. In those rows `author_is_self=1` (Kimi judging Kimi) "
                 "co-occurs with `predicted_self=0` and a low `score`, while the (author≠self, "
                 "pred=self, high score) cell is essentially absent — this inflates `b1` (the "
                 "M→Y slope on `predicted_self`) and therefore the indirect path `a1·b1`. After "
                 "removing those 11 prompts for all four authors, the belief channel either "
                 "collapses to ~0 (creativity, completeness C2/C3, constraint_adherence) or, in "
                 "the correctness and clarity dimensions, has intervals below zero.\n")
    lines.append("The style channel — based on the stylometric LR's leave-one-out posterior — "
                 "is less affected in this check, consistent with the 11-feature stylometric proxy capturing "
                 "a different low-level channel rather than only one model's off-topic behavior. "
                 "Per-judge horse-race (Claude raw +1.74 author; GPT-5.5 measured "
                 "style −0.51) remains the most defensible summary of the 4-judge data.\n")
    lines.append("This is a robustness caveat, **not a refutation** of PR #60/#65. The "
                 "qualitative pattern \"belief and measured style can pull in different directions\" stands; "
                 "the pooled magnitude of the belief channel does not.\n")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    print("Loading data...")
    df_long = pd.read_csv(os.path.join(REPO, "data/unified/unified_long.csv"))
    df_style = pd.read_csv(os.path.join(REPO, "data/derived/style_prob_self.csv"))
    keys = ["judge", "author", "prompt_id", "condition"]
    df = df_long.merge(df_style[keys + ["style_prob_self"]], on=keys, how="inner")
    df = df[df["condition"].isin(CONDS)].copy()
    print(f"Merged rows: {len(df):,}")
    df_drop = df[~df["prompt_id"].isin(OFF_TOPIC)].copy()
    print(f"After drop-11: {len(df_drop):,} rows on {df_drop['prompt_id'].nunique()} prompts")

    print("Pass 1/2: full (30 prompts)...")
    full = run_pass(df, "full")
    print("Pass 2/2: drop-11 (19 prompts)...")
    drop = run_pass(df_drop, "drop11")
    out = pd.concat([full, drop], ignore_index=True)
    csv_path = os.path.join(REPO, "results/subscale_horse_race_off_topic.csv")
    md_path = os.path.join(REPO, "results/subscale_horse_race_off_topic.md")
    out.to_csv(csv_path, index=False)
    write_report(out, md_path)
    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
